import Head from 'next/head'
import { Fragment } from 'react'

import MeetupList from '@/components/meetups/MeetupList';
import { MongoClient } from "mongodb";

function Home(props) {

  return <Fragment>

    <Head>
      <title>React Meetups</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <MeetupList meetups={props.meetups} />

  </Fragment>
}

export async function getStaticProps() {

  const client = await MongoClient.connect(
    'mongodb+srv://endritkanee:hLWBWfAJxCNpAm4T@cluster0.8arpyjj.mongodb.net/meetups?retryWrites=true&w=majority'
  );
  const db = client.db();
  const meetupCollection = db.collection('meetups');
  const meetups = await meetupCollection.find().toArray();

  client.close();


  return {
    props: {
      meetups: meetups.map(meetup => ({
        title: meetup.title,
        image: meetup.image,
        address: meetup.address,
        description: meetup.description,
        id: meetup._id.toString()
      }))
    },
    revalidate: 10
  }
}

export default Home;